# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 15) do

  create_table "article", :force => true do |t|
    t.column "tracker_id",       :integer
    t.column "title",            :string
    t.column "url",              :string
    t.column "content",          :text
    t.column "publication_date", :datetime
    t.column "fetch_date",       :datetime
    t.column "sent_flag",        :boolean
  end

  create_table "profile", :force => true do |t|
    t.column "user_id", :string
    t.column "email",   :string
  end

  create_table "rssfeed", :force => true do |t|
    t.column "title",       :string
    t.column "description", :string
    t.column "url",         :string
    t.column "tracked",     :boolean
    t.column "link",        :string
  end

  create_table "sent_article_archive", :force => true do |t|
    t.column "article_id",   :integer
    t.column "sending_date", :datetime
    t.column "user_id",      :string
  end

  create_table "subscription", :force => true do |t|
    t.column "tracker_id",    :integer
    t.column "date_lastmail", :datetime
    t.column "frequency",     :integer
    t.column "user_id",       :string
  end

  create_table "tracker", :force => true do |t|
    t.column "regex",      :string
    t.column "title",      :string
    t.column "type",       :string
    t.column "rssfeed_id", :integer
  end

end
